package edu.utsa.cs3443.mydosemate.controller;

import edu.utsa.cs3443.mydosemate.model.UserInputValidator;
import edu.utsa.cs3443.mydosemate.model.UserManager;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.Button;
import javafx.scene.control.Alert;
import javafx.scene.control.Label;
import javafx.scene.control.TextField;
import javafx.stage.Stage;

import java.io.IOException;

/**
 * Controller for the create-user screen.
 * Handles user input validation, account creation, and navigation
 * to the home dashboard.
 */
public class CreateUserController {

    @FXML
    private TextField firstNameField;

    @FXML
    private TextField lastNameField;

    @FXML
    private TextField emailField;

    @FXML
    private TextField phoneField;

    @FXML
    private Label firstNameErrorLabel;

    @FXML
    private Label lastNameErrorLabel;

    @FXML
    private Label emailErrorLabel;

    @FXML
    private Label phoneErrorLabel;

    @FXML
    private Button createAccountButton;

    private final UserManager userManager = new UserManager();

    /**
     * Validates the entered user information and creates the user's file.
     * If validation succeeds, the application navigates to the home dashboard.
     *
     * @param event the action event generated by clicking the Create Account button
     * @throws IOException if the user file or dashboard FXML cannot be loaded
     */
    @FXML
    private void createAccountClicked(ActionEvent event) throws IOException {
        String firstName = textOrEmpty(firstNameField);
        String lastName = textOrEmpty(lastNameField);
        String email = textOrEmpty(emailField);
        String phone = textOrEmpty(phoneField);

        try {
            String[] errors = UserInputValidator.validateUserCreation(
                    firstName,
                    lastName,
                    email,
                    phone
            );

            displayValidationErrors(errors);

            if (containsErrors(errors)) {
                return;
            }

            userManager.createUserFile(
                    firstName,
                    lastName,
                    email,
                    normalizePhone(phone)
            );

            navigateToDashboard(event);
        } catch (IllegalArgumentException exception) {
            showAlert("Invalid Input", exception.getMessage());
        } catch (IOException exception) {
            showAlert("Unable to Create Account", exception.getMessage());
        }
    }

    /**
     * Displays validation error messages underneath their corresponding fields.
     *
     * @param errors an array containing errors for first name, last name,
     *               email, and phone
     */
    private void displayValidationErrors(String[] errors) {
        if (firstNameErrorLabel != null) {
            firstNameErrorLabel.setText(errorText(errors[0]));
        }
        if (lastNameErrorLabel != null) {
            lastNameErrorLabel.setText(errorText(errors[1]));
        }
        if (emailErrorLabel != null) {
            emailErrorLabel.setText(errorText(errors[2]));
        }
        if (phoneErrorLabel != null) {
            phoneErrorLabel.setText(errorText(errors[3]));
        }
    }

    /**
     * Determines whether the validation result contains any errors.
     *
     * @param errors the array of validation error messages
     * @return true if at least one error is present; false otherwise
     */
    private boolean containsErrors(String[] errors) {
        for (String error : errors) {
            if (error != null) {
                return true;
            }
        }

        return false;
    }

    /**
     * Converts a nullable error message into text suitable for a JavaFX label.
     *
     * @param error the validation error message
     * @return an empty string if the error is null; otherwise the error message
     */
    private String errorText(String error) {
        return error == null ? "" : error;
    }

    /**
     * Removes formatting characters from a phone number before saving it.
     * A blank optional phone number remains blank.
     *
     * @param phone the phone number entered by the user
     * @return a phone number containing digits only
     */
    private String normalizePhone(String phone) {
        if (phone.isEmpty()) {
            return "";
        }

        return phone.replaceAll("\\D", "");
    }

    /**
     * Returns the trimmed value of a text field or an empty string if the field is null.
     *
     * @param field the text field to read
     * @return the trimmed field value, or empty string
     */
    private String textOrEmpty(TextField field) {
        return field == null || field.getText() == null ? "" : field.getText().trim();
    }

    /**
     * Shows a simple error dialog for validation or persistence failures.
     *
     * @param title the dialog title
     * @param message the dialog message
     */
    private void showAlert(String title, String message) {
        Alert alert = new Alert(Alert.AlertType.ERROR);
        alert.setTitle(title);
        alert.setHeaderText(null);
        alert.setContentText(message);
        alert.showAndWait();
    }

    /**
     * Loads the home dashboard and displays it in the current stage.
     *
     * @param event the event used to get the current application window
     * @throws IOException if the dashboard FXML file cannot be loaded
     */
    private void navigateToDashboard(ActionEvent event) throws IOException {
        FXMLLoader loader = new FXMLLoader(
                getClass().getResource(
                        "/edu/utsa/cs3443/mydosemate/view/home-dashboard.fxml"
                )
        );

        Parent root = loader.load();
        Scene scene = new Scene(root);

        Stage stage = (Stage) ((Node) event.getSource())
                .getScene()
                .getWindow();

        stage.setScene(scene);
        stage.show();
    }
}
